import React, { useContext } from "react";
import { LanguageContext } from "../../Context/LanguageContext";
import {
	TitleStyled,
	SubTitleStyled,
	ParagraphStyled,
	BulletStyled,
	BoldItems,
	PPContainer,
	PPTitle,
	SpecialSubTitleStyled,
	BulletBody,
	PPLinkStyled,
} from "./PrivacyPolicyStyled";

import { openInNewTab } from "../../Helpers/openNewTab";

function PrivacyPolicy() {
	const { data } = useContext(LanguageContext);

	return (
		<PPContainer>
			<PPTitle>{data.privacyPolicy.title}</PPTitle>
			<ParagraphStyled>{data.privacyPolicy.paragraph}</ParagraphStyled>
			<TitleStyled>{data.privacyPolicy.items[1].title}</TitleStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[1].paragraph[1]}
			</ParagraphStyled>

			<ParagraphStyled>
				{data.privacyPolicy.items[1].paragraph[2]}
			</ParagraphStyled>
			<TitleStyled>{data.privacyPolicy.items[2].title}</TitleStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[2].paragraph[1]}
			</ParagraphStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[2].paragraph[2]}
			</ParagraphStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[2].paragraph[3]}
			</ParagraphStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[2].paragraph[4]}
			</ParagraphStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[2].paragraph[5]}
			</ParagraphStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[2].paragraph[6]}
			</ParagraphStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[2].paragraph[7]}
			</ParagraphStyled>
			<TitleStyled>{data.privacyPolicy.items[3].title}</TitleStyled>
			<SubTitleStyled>
				{data.privacyPolicy.items[3].subTitles[1].subTitle}
			</SubTitleStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[3].subTitles[1].paragraph[1]}
			</ParagraphStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[3].subTitles[1].paragraph[2]}
			</ParagraphStyled>
			<SubTitleStyled>
				{data.privacyPolicy.items[3].subTitles[2].subTitle}
			</SubTitleStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[3].subTitles[2].paragraph[1]}
			</ParagraphStyled>
			<BulletStyled>
				{data.privacyPolicy.items[3].subTitles[2].bullets[1]}
			</BulletStyled>
			<BulletStyled>
				{data.privacyPolicy.items[3].subTitles[2].bullets[2]}
			</BulletStyled>
			<BulletStyled>
				{data.privacyPolicy.items[3].subTitles[2].bullets[3]}
			</BulletStyled>
			<BulletStyled>
				{data.privacyPolicy.items[3].subTitles[2].bullets[4]}
			</BulletStyled>
			<BulletStyled>
				{data.privacyPolicy.items[3].subTitles[2].bullets[5]}
			</BulletStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[3].subTitles[2].paragraph[2]}
			</ParagraphStyled>
			<SubTitleStyled>
				{data.privacyPolicy.items[3].subTitles[3].subtitle}
			</SubTitleStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[3].subTitles[3].paragraph[1]}
			</ParagraphStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[3].subTitles[3].paragraph[2]}
			</ParagraphStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[3].subTitles[3].paragraph[3]}
			</ParagraphStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[3].subTitles[3].paragraph[4]}
			</ParagraphStyled>
			<SubTitleStyled>
				{data.privacyPolicy.items[3].subTitles[4].subtitle}
			</SubTitleStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[3].subTitles[4].paragraph[1]}
			</ParagraphStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[3].subTitles[4].paragraph[2]}
			</ParagraphStyled>
			<BulletStyled>
				{data.privacyPolicy.items[3].subTitles[4].bullets[1]}
			</BulletStyled>
			<BulletStyled>
				{data.privacyPolicy.items[3].subTitles[4].bullets[2]}
			</BulletStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[3].subTitles[4].paragraph[3]}
			</ParagraphStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[3].subTitles[4].paragraph[4]}
			</ParagraphStyled>
			<TitleStyled>{data.privacyPolicy.items[4].title}</TitleStyled>
			<SpecialSubTitleStyled>
				{data.privacyPolicy.items[4].paragraph[1]}
				<BoldItems>
					{data.privacyPolicy.items[4].bolds[1]},
					{data.privacyPolicy.items[4].bolds[2]},
					{data.privacyPolicy.items[4].bolds[3]},
					{data.privacyPolicy.items[4].bolds[4]},
					{data.privacyPolicy.items[4].bolds[5]} and
					{data.privacyPolicy.items[4].bolds[1]}
				</BoldItems>
			</SpecialSubTitleStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[4].paragraph[2]}
			</ParagraphStyled>
			<SubTitleStyled>
				{data.privacyPolicy.items[4].subtitle[1]}
			</SubTitleStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[4].paragraph[3]}
			</ParagraphStyled>
			<SubTitleStyled>
				{data.privacyPolicy.items[4].subtitle[2]}
			</SubTitleStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[4].paragraph[4]}
			</ParagraphStyled>
			<BulletStyled>
				{data.privacyPolicy.items[4].bullets[1]}
			</BulletStyled>
			<BulletStyled>
				{data.privacyPolicy.items[4].bullets[2]}
				<PPLinkStyled
					onClick={() =>
						openInNewTab(
							`${data.privacyPolicy.items[4].links.google1}`
						)
					}
				>
					Privacy Policy
				</PPLinkStyled>
				-
				<PPLinkStyled
					onClick={() =>
						openInNewTab(
							`${data.privacyPolicy.items[4].links.google2}`
						)
					}
				>
					Opt Out.
				</PPLinkStyled>
			</BulletStyled>
			<SubTitleStyled>
				{data.privacyPolicy.items[4].subtitle[3]}
			</SubTitleStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[4].paragraph[5]}
			</ParagraphStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[4].paragraph[6]}
				<PPLinkStyled
					onClick={() =>
						openInNewTab(
							`${data.privacyPolicy.items[4].links.disquis1}`
						)
					}
				>
					Privacy Policy
				</PPLinkStyled>
				-
				<PPLinkStyled
					onClick={() =>
						openInNewTab(
							`${data.privacyPolicy.items[4].links.disquis2}`
						)
					}
				>
					Opt Out.
				</PPLinkStyled>
			</ParagraphStyled>
			<SubTitleStyled>
				{data.privacyPolicy.items[4].subtitle[4]}
			</SubTitleStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[4].paragraph[7]}
			</ParagraphStyled>
			<SubTitleStyled>
				{data.privacyPolicy.items[4].subtitle[5]}
			</SubTitleStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[4].paragraph[8]}
			</ParagraphStyled>
			<SubTitleStyled>
				{data.privacyPolicy.items[4].subtitle[6]}
			</SubTitleStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[4].paragraph[9]}
			</ParagraphStyled>
			<BulletStyled>
				{data.privacyPolicy.items[4].bullets[3]}
			</BulletStyled>
			<BulletStyled>
				{data.privacyPolicy.items[4].bullets[4]}
				<PPLinkStyled
					onClick={() =>
						openInNewTab(
							`${data.privacyPolicy.items[4].links.google1}`
						)
					}
				>
					Privacy Policy
				</PPLinkStyled>
				-
				<PPLinkStyled
					onClick={() =>
						openInNewTab(
							`${data.privacyPolicy.items[4].links.google2}`
						)
					}
				>
					Opt Out.
				</PPLinkStyled>
			</BulletStyled>
			<SubTitleStyled>
				{data.privacyPolicy.items[4].subtitle[7]}
			</SubTitleStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[4].paragraph[10]}
			</ParagraphStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[4].paragraph[11]}
			</ParagraphStyled>
			<SubTitleStyled>
				{data.privacyPolicy.items[4].subtitle[8]}
			</SubTitleStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[4].paragraph[12]}
			</ParagraphStyled>
			<BulletStyled>
				{data.privacyPolicy.items[4].bullets[5]}
			</BulletStyled>
			<BulletStyled>
				{data.privacyPolicy.items[4].bullets[6]}
				<PPLinkStyled
					onClick={() =>
						openInNewTab(
							`${data.privacyPolicy.items[4].links.google1}`
						)
					}
				>
					Privacy Policy
				</PPLinkStyled>
				-
				<PPLinkStyled
					onClick={() =>
						openInNewTab(
							`${data.privacyPolicy.items[4].links.google2}`
						)
					}
				>
					Opt Out.
				</PPLinkStyled>
			</BulletStyled>
			<SubTitleStyled>
				{data.privacyPolicy.items[4].subtitle[9]}
			</SubTitleStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[4].paragraph[13]}
			</ParagraphStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[4].paragraph[14]}
			</ParagraphStyled>
			<SubTitleStyled>
				{data.privacyPolicy.items[4].subtitle[10]}
			</SubTitleStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[4].paragraph[15]}
			</ParagraphStyled>
			<TitleStyled>{data.privacyPolicy.items[5].title}</TitleStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[5].paragraph[1]}
			</ParagraphStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[5].paragraph[2]}
			</ParagraphStyled>
			<BoldItems>
				<BulletStyled>
					{data.privacyPolicy.items[5].bullets[1].title}
				</BulletStyled>
			</BoldItems>
			<BulletBody>
				{data.privacyPolicy.items[5].bullets[1].paragraph}
			</BulletBody>
			<BoldItems>
				<BulletStyled>
					{data.privacyPolicy.items[5].bullets[2].title}
				</BulletStyled>
			</BoldItems>
			<BulletBody>
				{data.privacyPolicy.items[5].bullets[2].paragraph}
			</BulletBody>
			<BoldItems>
				<BulletStyled>
					{data.privacyPolicy.items[5].bullets[3].title}
				</BulletStyled>
			</BoldItems>
			<BulletBody>
				{data.privacyPolicy.items[5].bullets[3].paragraph}
			</BulletBody>
			<BoldItems>
				<BulletStyled>
					{data.privacyPolicy.items[5].bullets[4].title}
				</BulletStyled>
			</BoldItems>
			<BulletBody>
				{data.privacyPolicy.items[5].bullets[4].paragraph}
			</BulletBody>
			<BoldItems>
				<BulletStyled>
					{data.privacyPolicy.items[5].bullets[5].title}
				</BulletStyled>
			</BoldItems>
			<BulletBody>
				{data.privacyPolicy.items[5].bullets[5].paragraph}
			</BulletBody>
			<BoldItems>
				<BulletStyled>
					{data.privacyPolicy.items[5].bullets[6].title}
				</BulletStyled>
			</BoldItems>
			<BulletBody>
				{data.privacyPolicy.items[5].bullets[6].paragraph}
			</BulletBody>
			<BoldItems>
				<BulletStyled>
					{data.privacyPolicy.items[5].bullets[7].title}
				</BulletStyled>
			</BoldItems>
			<BulletBody>
				{data.privacyPolicy.items[5].bullets[7].paragraph}
			</BulletBody>
			<BoldItems>
				<BulletStyled>
					{data.privacyPolicy.items[5].bullets[8].title}
				</BulletStyled>
			</BoldItems>
			<BulletBody>
				{data.privacyPolicy.items[5].bullets[8].paragraph}
			</BulletBody>
			<SubTitleStyled>
				{data.privacyPolicy.items[5].subTitles[1]}
			</SubTitleStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[5].paragraph[3]}
			</ParagraphStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[5].paragraph[4]}
			</ParagraphStyled>

			<SubTitleStyled>
				{data.privacyPolicy.items[5].subTitles[2]}
			</SubTitleStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[5].paragraph[5]}
			</ParagraphStyled>
			<SubTitleStyled>
				{data.privacyPolicy.items[5].subTitles[3]}
			</SubTitleStyled>
			<SubTitleStyled>
				{data.privacyPolicy.items[5].subTitles[4]}
			</SubTitleStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[5].paragraph[6]}
			</ParagraphStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[5].paragraph[7]}
			</ParagraphStyled>
			<SubTitleStyled>
				{data.privacyPolicy.items[5].subTitles[5]}
			</SubTitleStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[5].paragraph[8]}
			</ParagraphStyled>
			<SubTitleStyled>
				{data.privacyPolicy.items[5].subTitles[6]}
			</SubTitleStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[5].paragraph[9]}
			</ParagraphStyled>
			<SubTitleStyled>
				{data.privacyPolicy.items[5].subTitles[7]}
			</SubTitleStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[5].paragraph[10]}
			</ParagraphStyled>
			<SubTitleStyled>
				{data.privacyPolicy.items[5].subTitles[8]}
			</SubTitleStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[5].paragraph[11]}
			</ParagraphStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[5].paragraph[12]}
			</ParagraphStyled>
			<SubTitleStyled>
				{data.privacyPolicy.items[5].subTitles[9]}
			</SubTitleStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[5].paragraph[13]}
			</ParagraphStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[5].paragraph[14]}
			</ParagraphStyled>
			<SubTitleStyled>
				{data.privacyPolicy.items[5].subTitles[10]}
			</SubTitleStyled>
			<SubTitleStyled>
				{data.privacyPolicy.items[5].subTitles[11]}
			</SubTitleStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[5].paragraph[15]}
			</ParagraphStyled>
			<SubTitleStyled>
				{data.privacyPolicy.items[5].subTitles[12]}
			</SubTitleStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[5].paragraph[16]}
			</ParagraphStyled>
			<SubTitleStyled>
				{data.privacyPolicy.items[5].subTitles[13]}
			</SubTitleStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[5].paragraph[17]}
			</ParagraphStyled>
			<SubTitleStyled>
				{data.privacyPolicy.items[5].subTitles[14]}
			</SubTitleStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[5].paragraph[18]}
			</ParagraphStyled>
			<SubTitleStyled>
				{data.privacyPolicy.items[5].subTitles[15]}
			</SubTitleStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[5].paragraph[19]}
			</ParagraphStyled>
			<SubTitleStyled>
				{data.privacyPolicy.items[5].subTitles[16]}
			</SubTitleStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[5].paragraph[20]}
			</ParagraphStyled>
			<SubTitleStyled>
				{data.privacyPolicy.items[5].subTitles[17]}
			</SubTitleStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[5].paragraph[21]}
			</ParagraphStyled>
			<SubTitleStyled>
				{data.privacyPolicy.items[5].subTitles[18]}
			</SubTitleStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[5].paragraph[22]}
			</ParagraphStyled>
			<SubTitleStyled>
				{data.privacyPolicy.items[5].subTitles[19]}
			</SubTitleStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[5].paragraph[23]}
			</ParagraphStyled>
			<SubTitleStyled>
				{data.privacyPolicy.items[5].subTitles[20]}
			</SubTitleStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[5].paragraph[24]}
			</ParagraphStyled>
			<SubTitleStyled>
				{data.privacyPolicy.items[5].subTitles[21]}
			</SubTitleStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[5].paragraph[25]}
			</ParagraphStyled>
			<ParagraphStyled>
				{data.privacyPolicy.items[5].paragraph[26]}
			</ParagraphStyled>
		</PPContainer>
	);
}

export default PrivacyPolicy;
